"""Shared social-science analysis definitions used by the schema generator."""
import json
import random

rng=random.Random(341)
survey=[]; social=[]
for i in range(48):
    first=rng.gauss(0,1); second=.5*first+rng.gauss(0,1)
    survey.append([round(3+b*first+rng.gauss(0,.55),3) for b in (1,.8,1.2)]+[round(3+b*second+rng.gauss(0,.55),3) for b in (1,.9,1.1)])
    x=rng.gauss(0,1); m=.7*x+rng.gauss(0,.6); y=.3*x+.8*m+.25*x*m+rng.gauss(0,.7)
    social.append([round(v,3) for v in (x,m,y)])
def data(rows): return json.dumps(rows,separators=(',',':'))
REG='[[0,2],[1,4],[2,3],[3,8],[4,7],[5,9],[6,10],[7,12],[8,11],[9,15],[10,17],[11,16]]'
COUNTS=data([[x,y] for x,counts in enumerate(((0,0,0,1,2,3),(0,0,1,2,3,5),(0,0,1,3,5,8),(0,0,2,4,7,10))) for y in counts])
SPECS=[
 ('cronbach','Cronbach α reliability','Cronbach α 신뢰도','table',',raw',data(survey[:24]),'Rows are subjects, columns are items; raw or standardized alpha. Reverse-code items first. Returns corrected item-total correlations and alpha if deleted. Alpha measures internal consistency.','행은 대상, 열은 문항; raw·standardized α. 역문항은 먼저 역코딩합니다. 수정 문항-총점 상관·문항 삭제 시 α를 제공합니다. α는 내적 일관성을 나타냅니다.'),
 ('efa','Exploratory factor analysis (EFA)','탐색적 요인분석 (EFA)','table',',2,oblimin,pa,0,0,0.95',data(survey),'Select numeric item columns. Extraction: pa (principal axis, default), ml (normal maximum likelihood common factors), or pca (principal components). Enter a factor count or parallel for automatic selection. Rotations: oblimin (default, delta 0), varimax, none or promax (power 4). Arguments: data,count,rotation,extraction,parallel simulations,seed,percentile. Parallel simulations: 0 = off; automatic selection defaults to 100, percentile 0.95. Reports KMO, Bartlett, communalities, pattern and structure loadings, factor correlations and regression scores. PA/ML factor counts use SMC-reduced common roots for parallel analysis; PCA uses correlation eigenvalues. For correlated factors, interpret communalities with the factor correlations.','숫자 문항 열을 선택합니다. 추출: 주축요인법(pa, 기본)·최대우도법(ml, 정규 공통요인)·주성분(pca). 요인 수 또는 자동 선택 parallel을 입력합니다. 회전: oblimin(기본, delta 0)·varimax·none·promax(지수 4). 인수: 자료,요인 수,회전,추출,병렬분석 횟수,시드,백분위. 횟수 0은 끔, 자동 선택 기본값은 100회·백분위 0.95입니다. KMO·Bartlett·공통성·패턴/구조 적재량·요인 상관·회귀 점수를 제공합니다. 병렬분석은 주축요인법에서 SMC 축소 고유값, 주성분에서 상관 고유값을 사용합니다. 사각회전의 공통성은 요인 상관을 함께 반영해 해석합니다.'),
 ('cfa','Confirmatory factor analysis (CFA)','확인적 요인분석 (CFA)','table',',[1,1,1,2,2,2]',data(survey),'Choose ML for continuous indicators or WLSMV for numeric ordinal category codes (ordered numerically). No fixed minimum indicator count per factor; identification is checked using model df and the information matrix. The first pure primary indicator (otherwise the first primary indicator) fixes its primary loading at 1. Cross-loadings use [indicator,factor] pairs and may also be added on marker indicators. ML supports complete rows or FIML under MCAR/MAR. WLSMV requires complete rows and uses probit thresholds/polychoric correlations, DWLS, full influence-covariance sandwich SEs and scaled-shifted mean/variance-adjusted T3. Measurement invariance: configural (group free), metric (equal loadings), scalar (also equal intercepts for ML or response thresholds for WLSMV), strict (also equal residual variances). Scalar/strict estimate other-group latent means, fixing reference means to zero. Multi-group scalar/strict WLSMV requires the same observed categories in each group, at least three per indicator; reference residual variances are 1, scalar frees them in other groups and strict fixes all to 1. Reports chi-square, df, p, CFI, TLI, RMSEA and complete-data SRMR. WLSMV fit indices use adjusted tests; adjusted chi-squares cannot be subtracted for difference testing. Arguments: data,factors,cross-loadings,complete/fiml,group IDs,configural/metric/scalar/strict,ml/wlsmv.','연속형 지표는 ML, 숫자 범주 코드의 서열형 지표는 WLSMV를 선택합니다(범주 순서는 숫자순). 요인당 문항 수 하한 대신 모형 자유도·정보행렬로 식별 가능성을 판단합니다. 교차적재가 없는 첫 주 지표(없으면 첫 주 지표)의 주 적재량을 1로 고정합니다. 교차적재는 [지표,요인] 쌍이며 척도 기준 지표에도 추가할 수 있습니다. ML은 완전자료 또는 MCAR/MAR 가정의 FIML, WLSMV는 완전자료를 사용합니다. WLSMV: probit 역치·다분상관, DWLS, 전체 영향함수 공분산의 샌드위치 표준오차, 평균·분산 보정 T3 검정. 측정동일성: configural(집단별 자유), metric(적재량 동일), scalar(ML은 절편, WLSMV는 반응 역치도 동일), strict(잔차분산도 동일). scalar/strict는 기준 집단 잠재평균을 0으로 고정하고 다른 집단 잠재평균을 추정합니다. 다집단 scalar/strict WLSMV는 지표마다 집단 간 같은 관측 범주가 3개 이상 필요합니다. 기준 잔차분산은 1, scalar는 다른 집단에서 자유 추정, strict는 모두 1입니다. χ²·df·p·CFI·TLI·RMSEA·완전자료 SRMR을 제공합니다. WLSMV 적합도는 보정 검정 기준이며 보정 χ²를 단순 차감한 차이검정은 사용할 수 없습니다. 인수: 자료,요인,교차적재,complete/fiml,집단 ID,configural/metric/scalar/strict,ml/wlsmv.'),
 ('sem','Structural equation model (SEM)','구조방정식 모형 (SEM)','table',',[1,1,1,2,2,2],[[1,2]]',data(survey),'Choose ML for continuous indicators or WLSMV for numeric ordinal category codes (ordered numerically). No fixed minimum indicator count per factor; identification is checked using model df and the information matrix. The first pure primary indicator (otherwise the first primary indicator) fixes its primary loading at 1. Cross-loadings use [indicator,factor] pairs and may also be added on marker indicators. ML supports complete rows or FIML under MCAR/MAR. WLSMV requires complete rows and uses probit thresholds/polychoric correlations, DWLS, full influence-covariance sandwich SEs and scaled-shifted mean/variance-adjusted T3. Measurement invariance: configural (group free), metric (equal loadings), scalar (also equal intercepts for ML or response thresholds for WLSMV), strict (also equal residual variances). Scalar/strict estimate other-group latent means, fixing reference means to zero. Multi-group scalar/strict WLSMV requires the same observed categories in each group, at least three per indicator; reference residual variances are 1, scalar frees them in other groups and strict fixes all to 1. Reports chi-square, df, p, CFI, TLI, RMSEA and complete-data SRMR. WLSMV fit indices use adjusted tests; adjusted chi-squares cannot be subtracted for difference testing. Add acyclic latent paths [source,target]; exogenous factors may covary, endogenous disturbances and indicator errors are independent. Arguments: data,factors,paths,cross-loadings,complete/fiml,group IDs,configural/metric/scalar/strict,ml/wlsmv.','연속형 지표는 ML, 숫자 범주 코드의 서열형 지표는 WLSMV를 선택합니다(범주 순서는 숫자순). 요인당 문항 수 하한 대신 모형 자유도·정보행렬로 식별 가능성을 판단합니다. 교차적재가 없는 첫 주 지표(없으면 첫 주 지표)의 주 적재량을 1로 고정합니다. 교차적재는 [지표,요인] 쌍이며 척도 기준 지표에도 추가할 수 있습니다. ML은 완전자료 또는 MCAR/MAR 가정의 FIML, WLSMV는 완전자료를 사용합니다. WLSMV: probit 역치·다분상관, DWLS, 전체 영향함수 공분산의 샌드위치 표준오차, 평균·분산 보정 T3 검정. 측정동일성: configural(집단별 자유), metric(적재량 동일), scalar(ML은 절편, WLSMV는 반응 역치도 동일), strict(잔차분산도 동일). scalar/strict는 기준 집단 잠재평균을 0으로 고정하고 다른 집단 잠재평균을 추정합니다. 다집단 scalar/strict WLSMV는 지표마다 집단 간 같은 관측 범주가 3개 이상 필요합니다. 기준 잔차분산은 1, scalar는 다른 집단에서 자유 추정, strict는 모두 1입니다. χ²·df·p·CFI·TLI·RMSEA·완전자료 SRMR을 제공합니다. WLSMV 적합도는 보정 검정 기준이며 보정 χ²를 단순 차감한 차이검정은 사용할 수 없습니다. 비순환 잠재 경로 [출발,도착]를 지정합니다. 외생 요인 간 상관, 독립 내생 교란·지표 오차를 가정합니다. 인수: 자료,요인,경로,교차적재,complete/fiml,집단 ID,configural/metric/scalar/strict,ml/wlsmv.'),
 ('manova','MANOVA','MANOVA (다변량 분산분석)','table','',data([[i//8+1,round(r[0],3),round(r[3],3)] for i,r in enumerate(survey[:24])]),'One-way: group column followed by response columns. Factorial: manova(data,factorial,factor count,interaction order), categorical factors first; Type III tests with sum contrasts. Repeated: manova(wide data,repeated,occasions), one subject per row and equal-sized response blocks in occasion order. Tests mean equality across occasions using within-subject contrasts. Reports Pillai, Wilks Rao, Hotelling–Lawley F and Roy upper-bound F. Use complete data and nonsingular residual covariance; independent subjects and normal errors are assumed, with equal group covariance for independent-group designs.','일요인: 그룹 열 뒤에 종속변수 열을 배치합니다. 요인설계: manova(자료,factorial,요인 수,상호작용 차수), 범주 요인 열을 먼저 배치하며 합 대비의 Type III 검정을 사용합니다. 반복측정: manova(넓은 자료,repeated,시점 수), 행당 대상 1명·시점 순서의 동일 크기 반응 블록입니다. 대상 내 대비로 시점 간 평균 동일성을 검정합니다. Pillai·Wilks Rao·Hotelling–Lawley F·Roy 상한 F를 제공합니다. 완전자료·비특이 잔차 공분산이 필요하며 독립 대상·정규 오차, 독립 그룹 설계의 등공분산을 가정합니다.'),
 ('mediation','Mediation analysis','매개 분석','table',',2000,0',data(social[:24]),'Rows: X, M, optional covariates, Y. Single continuous mediator; adjusted OLS direct, total and indirect a×b effects, seeded row-bootstrap percentile CI and Sobel approximation.','열: X·M·선택적 공변량·Y. 단일 연속형 매개변수; 조정 OLS 직접·총·간접 a×b 효과, 시드 기반 행 부트스트랩 백분위 CI·Sobel 근사.'),
 ('moderation','Moderation analysis','조절 분석','table','',data(social[:24]),'Rows: X, W, optional covariates, Y. Centered X/W and X×W interaction; conditional slopes at W mean ± SD with full covariance t inference. Continuous moderator, independent OLS errors.','열: X·W·선택적 공변량·Y. 중심화 X/W·X×W 상호작용; W 평균±SD의 조건부 기울기·전체 공분산 t 추론. 연속형 조절변수·독립 OLS 오차.'),
 ('cramerv','Cramér’s V','Cramér의 V','table','','[[20,5],[7,18]]','Nonnegative integer contingency counts; uncorrected Pearson χ² and Cramér’s V. Independent observations; sparse counts can invalidate χ² p values.','음이 아닌 정수 분할표 빈도; 보정 없는 Pearson χ²·Cramér의 V. 독립 관측; 희소 빈도에서는 χ² p값이 부정확할 수 있습니다.'),
 ('phi','Phi coefficient','phi 계수','table','','[[20,5],[7,18]]','Signed phi for a 2×2 integer count table; swapping one category order reverses its sign. No Yates correction.','2×2 정수 빈도표의 부호 있는 phi; 한 변수의 범주 순서를 바꾸면 부호가 반전됩니다. Yates 보정 없음.'),
 ('cohenkappa','Cohen’s κ agreement','Cohen의 κ 일치도','table',',unweighted','[[25,4,2],[3,20,5],[1,6,24]]','Two-rater square count table with common category order. Unweighted, linear or quadratic kappa; multinomial delta-method SE and asymptotic Wald CI. Weighted categories must be ordered. Observed/expected agreement use the selected weights; exact agreement is also reported.','공통 범주 순서의 두 평가자 정방 빈도표. 무가중·선형·제곱 가중 κ; 다항 델타법 SE·점근 Wald CI. 가중 범주는 순서형이어야 합니다. 관측·기대 일치율은 선택한 가중치를 반영하며 정확 일치율도 제공합니다.'),
 ('dunn','Dunn post-hoc test','Dunn 사후검정','table',',holm','[[1,2,4],[2,3,6],[3,5,8],[4,7,9]]','List of independent sample lists, then holm (default), bonferroni, fdr or none. Pooled midranks, tie correction, two-sided normal p values. Retains the Kruskal–Wallis pooled rank scale.','독립 표본 목록들의 목록과 holm(기본)·bonferroni·fdr·none. 전체 평균순위·동점 보정·양측 정규 p값. Kruskal–Wallis의 전체 순위 척도를 유지합니다.'),
 ('discriminantanalysis','Discriminant analysis (LDA/QDA)','판별분석 (LDA/QDA)','table',',lda,empirical','[[1,2,1],[2,1,1],[1,1,1],[2,3,1],[4,5,2],[5,4,2],[4,4,2],[5,6,2]]','Rows: features, class. LDA pooled / QDA separate unbiased covariances; empirical/equal priors. Optional fourth argument: new feature rows. Training confusion and accuracy use the fitted sample.','열: 변수·분류. LDA 합동 / QDA 개별 불편 공분산; 경험·동일 사전확률. 선택적 넷째 인수: 새 변수 행. 학습 혼동표·정확도는 적합에 사용한 표본 기준입니다.'),
 ('quantreg','Quantile regression','분위회귀','table',',0.5',REG,'Rows: predictors, response; quantile in (0,1). IRLS with subgradient optimality check; asymptotic Gaussian-kernel sandwich / Hall–Sheather bandwidth if residual density supports inference.','열: 설명변수·반응; (0,1)의 분위수. 부분기울기 최적성 검사 IRLS; 잔차 밀도가 추론을 허용하면 Gaussian 커널 샌드위치 / Hall–Sheather 대역폭의 점근 추론.'),
 ('zeroinflated','Zero-inflated regression (ZIP/ZINB)','영과잉 회귀 (ZIP/ZINB)','table',',poisson,intercept',COUNTS,'Rows: predictors, integer counts. Poisson or estimated-alpha NB2 count mixture with logit structural zeros; inflation intercept or same predictors. Joint ML Wald inference.','열: 설명변수·정수 빈도. Poisson 또는 alpha 추정 NB2와 구조적 0의 logit 혼합; 영과잉 절편 또는 같은 설명변수. 공동 ML Wald 추론;'),
 ('tobit','Tobit censored regression','Tobit 검열 회귀','table',',0,none','[[0,0],[1,0],[2,1],[3,3],[4,3],[5,6],[6,5],[7,8],[8,9],[9,8],[10,11],[11,12]]','Rows: predictors, observed response; lower bound (default 0), upper bound (default none). Type-I normal censoring, joint ML coefficient/sigma inference. Values at bounds are censored; coefficients refer to the latent response.','열: 설명변수·관측 반응; 하한(기본 0)·상한(기본 none). Type-I 정규 검열·공동 ML 계수/sigma 추론. 경계값은 검열 관측, 계수는 잠재 반응 기준.'),
 ('hcluster','Hierarchical clustering','계층적 군집분석','table',',2,ward,1','[[1,1],[1,2],[2,1],[8,8],[8,9],[9,8]]','Independent agglomerative analysis; clusters, single/complete/average/Ward Euclidean linkage, standardize 1/0. Returns all merges, heights, sizes and cut assignments. Leaves 1…n, merge nodes n+1…2n−1.','독립 응집 분석; 군집 수·single/complete/average/Ward 유클리드 연결·표준화 1/0. 전체 병합·거리·크기·절단 배정. 잎 1…n, 병합 노드 n+1…2n−1.'),
]

REPORT_HELP={
 'efa':(' Loading plots show selected rotated components/factors with selectable axes and item labels. PA/PCA explained variance (%) and cumulative explained variance (%) use extraction eigenvalues / standardized item count; ML uses unrotated common squared-loading sums / item count; Varimax also reports rotated squared-loading shares. Oblique pattern squared-loading sums are not additive variance shares.',
        ' 적재량 시각화는 선택한 회전 후의 주성분·요인과 문항 이름을 표시하며 축을 선택할 수 있습니다. PA·PCA 설명 분산(%)·누적 설명 분산(%)은 추출 고유값 / 표준화 문항 수, ML은 회전 전 공통 제곱적재량 합 / 문항 수 기준이며 Varimax는 회전 후 제곱적재량 합의 비율도 제공합니다. 사각회전의 패턴 제곱적재량 합은 누적 가능한 분산 비율이 아닙니다.'),
 'cfa':(' Reports fully standardized loadings and paths with delta-method 95% Wald confidence intervals, including standardized marker uncertainty. The diagram uses ellipses for latent factors, rectangles for indicators, standardized coefficients with intervals, and latent R² = 1 − disturbance variance / total latent variance for endogenous factors (not applicable to exogenous factors). Multi-group diagrams are selectable by group; WLSMV loadings describe underlying probit responses. Use Fit diagram to screen to scale the whole diagram to the available width and height; Original size restores scrolling.',
        ' 완전 표준화 요인적재량·경로계수와 델타 방법의 95% Wald 신뢰구간을 제공하며 고정 첫 적재량의 표준화 불확실성도 반영합니다. 도표는 잠재변수(타원)·관측지표(사각형)·표준화 계수와 신뢰구간을 표시합니다. 내생 잠재변수 R² = 1 − 교란분산 / 전체 잠재분산을 결과와 도표에 표시하며 외생변수에는 해당하지 않습니다. 다집단 도표는 집단을 선택해 볼 수 있고 WLSMV 적재량은 기저 probit 반응 척도입니다. 화면에 맞추기는 전체 도표를 표시 영역의 가로·세로 크기에 맞게 축소하며 원래 크기로 스크롤 보기를 복원합니다.')
}
REPORT_HELP['sem']=REPORT_HELP['cfa']
for model in ('cfa','sem'):
    REPORT_HELP[model]=(REPORT_HELP[model][0]+' Model diagnostics show convergence, maximum absolute gradient, local identification and the minimum residual variance ratio. Numerical checks do not establish model validity; review fit indices, residuals, intervals and study design together. Fit assessment is unavailable with zero model degrees of freedom.',
                        REPORT_HELP[model][1]+' 모형 진단은 수렴·기울기 절댓값 최댓값·국소 모수 식별·최소 잔차 분산 비율을 표시합니다. 수치 검사로 모형 타당성을 입증할 수 없으며 적합도 지수·잔차·신뢰구간·연구 설계를 함께 확인하세요. 모형 자유도가 0이면 적합도 평가가 불가합니다.')
REPORT_HELP['efa']=(REPORT_HELP['efa'][0]+' Run CFA transfers the analyzed data and column order, assigning each indicator to its largest absolute rotated loading. Review/edit memberships; model df and the fitted information matrix determine identification.',
                    REPORT_HELP['efa'][1]+' CFA 실행은 분석 당시의 데이터·컬럼 순서를 유지하고 절댓값이 가장 큰 회전 적재량으로 컬럼 소속을 배정합니다. 소속을 확인·수정할 수 있으며 모형 자유도·추정 정보행렬로 식별 가능성을 확인합니다.')
REPORT_HELP['efa']=(REPORT_HELP['efa'][0]+' Cross-loading detection uses secondary absolute rotated pattern loadings ≥ 0.30 by default. Change the cutoff, disable automatic inclusion or uncheck individual candidates before CFA. This is a screening rule, not a significance test.',
                    REPORT_HELP['efa'][1]+' 교차적재는 주 요인 이외의 회전 패턴 적재량 절댓값이 기본 0.30 이상인 경우 검출합니다. 기준값 변경·자동 반영 해제·후보별 제외 후 CFA에 반영할 수 있습니다. 이는 후보 선별 기준이며 유의성 검정이 아닙니다.')
REPORT_HELP['cfa']=(REPORT_HELP['cfa'][0]+' Run SEM keeps the fitted measurement model, cross-loadings, data, group IDs and estimation options. Enter acyclic latent paths before execution; structural direction is not inferred from CFA.',
                    REPORT_HELP['cfa'][1]+' SEM 실행은 적합한 측정모형·교차적재·데이터·집단 ID·추정 옵션을 유지합니다. 비순환 잠재 경로를 입력한 뒤 실행하며 구조 경로 방향은 CFA에서 자동 추정하지 않습니다.')
for model in ('cfa','sem'):
    REPORT_HELP[model]=(REPORT_HELP[model][0]+' Indicator R² reports variance explained by the latent factors in each observed indicator, including factor covariance for cross-loadings; WLSMV uses the underlying probit response. Indicator R² is displayed in both tables and diagrams.',
                        REPORT_HELP[model][1]+' 관측지표별 R²는 각 컬럼에서 잠재요인이 설명하는 분산 비율이며 교차적재 시 요인 간 공분산도 반영합니다. WLSMV는 기저 probit 반응 척도이며 결과표와 도표 모두에 표시합니다.')
REPORT_HELP['efa']=(REPORT_HELP['efa'][0]+' ML assumes multivariate normal complete data and fits positive uniquenesses by normal likelihood. ML variance percentages use unrotated common squared-loading sums / item count; ML χ² uses the Bartlett correction and reports model df/p. Boundary uniqueness or unidentified factor counts require revising the model.',
                    REPORT_HELP['efa'][1]+' ML은 완전자료의 다변량 정규성을 가정하며 양의 고유분산을 우도로 추정합니다. ML 설명 분산은 회전 전 공통요인 제곱적재량 합 / 문항 수 기준입니다. ML χ²는 Bartlett 보정과 모형 df·p를 제공하며 고유분산 경계·식별 불가 요인 수에서는 모형을 수정해야 합니다.')
for model in ('cfa','sem'):
    REPORT_HELP[model]=(REPORT_HELP[model][0]+' Optional arguments after estimator: residual covariance pairs [[2,3],[5,6]], modification indices 0 (Off, default) / 1 (On), bootstrap count 0 (default), seed 0. Pairs refer to selected indicator positions; strict invariance shares their raw covariances. MI/EPC list single additional cross-loadings, residual covariances and acyclic paths. ML uses expected-information efficient scores; WLSMV uses robust DWLS scores, not a difference of adjusted T3 tests. Review theory before adding parameters. Residual covariances and options transfer from CFA to SEM.',
                        REPORT_HELP[model][1]+' 추정 방식 뒤의 선택 인수: 잔차 공분산 쌍 [[2,3],[5,6]], 수정지수 0(Off·꺼짐, 기본)·1(On·켜짐), 부트스트랩 횟수 0(기본), 시드 0. 쌍은 선택 지표 순서의 번호이며 strict에서는 원척도 공분산도 집단 간 공유합니다. MI·EPC는 추가 가능한 교차적재·잔차 공분산·비순환 경로를 제시합니다. ML은 기대정보 효율 점수, WLSMV는 강건 DWLS 점수이며 보정 T3의 차이가 아닙니다. 이론적 근거를 확인한 후 모수를 추가하세요. CFA에서 SEM으로 잔차 공분산·옵션도 유지합니다.')
REPORT_HELP['sem']=(REPORT_HELP['sem'][0]+' Direct, total indirect and total latent effects sum products over all specified directed paths, with raw/standardized delta-method 95% Wald intervals. Bootstrap count: 0 = off, otherwise at least 20 (1000 or more recommended for final inference). Stratified case resampling refits the full model each draw; seeded 95% percentile CIs are shown separately. Execution time/work budgets scale with the requested refits; manual cancellation remains available. Failed refits are counted; CI requires at least 20 and 80% successful draws. Coefficient products alone do not establish causal mediation.',
                    REPORT_HELP['sem'][1]+' 지정한 방향 경로의 곱을 합산해 직접·총 간접·총 효과와 원척도·표준화 델타법 95% Wald 구간을 제공합니다. 부트스트랩 횟수: 0=끔, 사용 시 최소 20회(최종 추론에는 1000회 이상 권장). 집단별 행을 복원추출하여 매번 전체 모형을 재적합하고 시드 기반 95% 백분위 CI를 따로 표시합니다. 요청한 재적합 횟수에 맞춰 시간·작업량 한도를 늘리며 사용자가 취소할 수 있습니다. 실패 재적합을 집계하며 성공이 최소 20회·80% 이상일 때만 구간을 제공합니다. 경로계수의 곱만으로 인과적 매개를 입증하지는 않습니다.')
SPECS=[(*spec[:6],spec[6]+REPORT_HELP.get(spec[0],('',''))[0],spec[7]+REPORT_HELP.get(spec[0],('',''))[1]) for spec in SPECS]

def forms(field,col,multi,group_fields):
    choice=lambda key,en,ko,default,values: field(key,en,ko,'choice',default,[(v,e,k) for v,e,k in values])
    scaling=choice('standardize','Scaling','척도','1',[('1','Standardize','표준화'),('0','Raw scale','원척도')])
    features=[multi('columns','Feature / item columns','변수·문항 열')]
    regression=[col('response','Response','반응 열',-1),multi('predictors','Predictors','설명변수 열')]
    measurement=features+[field('factors','Primary factor IDs in selected order','선택 순서의 주 요인 ID','text','1,1,1,2,2,2'),
        field('cross','Cross-loadings: indicator,factor;…','교차적재: 선택 지표 번호,요인;…','text',''),
        field('residual','Residual covariance pairs: indicator,indicator;…','잔차 공분산 쌍: 선택 지표 번호,지표 번호;…','text',''),
        choice('modindices','Modification indices','수정지수','0',[('0','Off','Off (꺼짐)'),('1','On','On (켜짐)')]),
        choice('estimator','Estimator','추정 방식','ml',[('ml','ML (continuous)','ML (연속형)'),('wlsmv','WLSMV (ordinal)','WLSMV (서열형)')]),
        dict(choice('missing','Missing data','결측 자료','complete',[('complete','Complete rows required','완전한 행 필요'),('fiml','FIML (MAR, continuous)','FIML (MAR, 연속형)')]),when={'estimator':['ml']}),
        choice('groupMode','Groups','집단','single',[('single','Single group','단일 집단'),('multi','Multiple groups','다집단')]),
        dict(col('group','Group column','집단 열',0),when={'groupMode':['multi']}),
        dict(choice('invariance','Measurement invariance','측정동일성','configural',[('configural','Configural (group free)','형태 (집단별 자유)'),('metric','Metric (equal loadings)','측정 (적재량 동일)'),('scalar','Scalar (equal loadings & intercepts/thresholds)','Scalar (적재량·절편/역치 동일)'),('strict','Strict (scalar & equal residual variances)','Strict (scalar·잔차분산 동일)')]),when={'groupMode':['multi']})]
    layout=choice('layout','Data layout','자료 형태','counts',[('counts','Contingency counts','분할표 빈도'),('pairs','Paired categories','범주 쌍')])
    categorical=[layout,dict(multi('columns','Count columns','빈도 열'),when={'layout':['counts']}),dict(col('first','First variable / rater','첫 변수·평가자',0),when={'layout':['pairs']}),dict(col('second','Second variable / rater','둘째 변수·평가자',1),when={'layout':['pairs']})]
    social=[col('x','Predictor X','설명변수 X',0),col('middle','Mediator M / moderator W','매개 M·조절 W',1),col('response','Outcome Y','결과 Y',-1),field('covariates','Covariate columns (optional)','공변량 열 (선택)','columns','')]
    return {
      'cronbach':features+[choice('mode','Alpha','α','raw',[('raw','Raw','원척도'),('standardized','Standardized','표준화')])],
      'efa':features+[field('factors','Factor count or parallel','요인 수 또는 parallel','text','2'),
        choice('extraction','Extraction','추출','pa',[('pa','Principal axis (common factors)','주축요인법 (공통요인)'),('ml','Maximum likelihood (common factors)','최대우도법 (공통요인)'),('pca','Principal components (PCA)','주성분 (PCA)')]),
        choice('rotation','Rotation','회전','oblimin',[('varimax','Varimax (orthogonal)','Varimax (직교)'),('promax','Promax (oblique, power 4)','Promax (사각, 지수 4)'),('oblimin','Oblimin (oblique, delta 0)','Oblimin (사각, delta 0)'),('none','None','없음')]),
        field('parallelSamples','Parallel simulations (0 = off; parallel count uses 100)','병렬분석 횟수 (0=끔; parallel 자동 선택은 100회)','number','0'),field('seed','Seed','시드','number','0'),field('percentile','Parallel percentile (0–1)','병렬분석 백분위 (0~1)','number','0.95')],
      'cfa':measurement,'sem':measurement+[field('paths','Latent paths: source,target;…','잠재 경로: 출발,도착;…','text','1,2'),
        field('bootstrapSamples','Effect bootstrap samples (0 = off)','효과 부트스트랩 횟수 (0=끔)','number','0'),field('bootstrapSeed','Bootstrap seed','부트스트랩 시드','number','0')],
      'manova':[choice('design','Design','설계','oneway',[('oneway','One factor','일요인'),('factorial','Factorial (Type III)','요인설계 (Type III)'),('repeated','Repeated (wide rows)','반복측정 (대상별 넓은 행)')]),
        dict(col('group','Group','그룹 열',0),when={'design':['oneway']}),dict(multi('factorColumns','Factor columns','요인 열'),default='0,1',when={'design':['factorial']}),
        multi('responses','Response columns (occasion blocks for repeated)','종속변수 열 (반복측정은 시점별 블록 순서)'),
        dict(field('order','Interaction order','상호작용 차수','number','2'),when={'design':['factorial']}),
        dict(field('occasions','Repeated occasions','반복 시점 수','number','3'),when={'design':['repeated']})],
      'mediation':social+[field('samples','Bootstrap samples','부트스트랩 횟수','number','2000'),field('seed','Seed','시드','number','0')],
      'moderation':social,'cramerv':categorical,'phi':categorical,
      'cohenkappa':categorical+[choice('weights','Weights','가중치','unweighted',[('unweighted','Unweighted','무가중'),('linear','Linear','선형'),('quadratic','Quadratic','제곱')]),dict(field('categories','Category order (comma separated; optional for unweighted)','범주 순서 (쉼표 구분; 무가중은 선택)','text',''),when={'layout':['pairs']})],
      'dunn':group_fields+[choice('adjustment','P-value adjustment','p값 보정','holm',[(v,e,e) for v,e in [('holm','Holm'),('bonferroni','Bonferroni'),('fdr','FDR (BH)'),('none','None')]])],
      'discriminantanalysis':[col('response','Class','분류 열',-1),multi('predictors','Features','변수 열'),choice('method','Method','방법','lda',[('lda','LDA','LDA'),('qda','QDA','QDA')]),choice('prior','Class priors','분류 사전확률','empirical',[('empirical','Empirical','경험 빈도'),('equal','Equal','동일')])],
      'quantreg':regression+[field('quantile','Quantile','분위수','number','0.5')],
      'zeroinflated':regression+[choice('family','Count family','빈도 분포','poisson',[('poisson','Poisson (ZIP)','Poisson (ZIP)'),('nbinom','Negative binomial (ZINB2)','음이항 (ZINB2)')]),choice('inflation','Inflation predictors','영과잉 설명변수','intercept',[('intercept','Intercept only','절편만'),('same','Same predictors','같은 설명변수')])],
      'tobit':regression+[field('lower','Lower bound (none = absent)','하한 (none = 없음)','text','0'),field('upper','Upper bound (none = absent)','상한 (none = 없음)','text','none')],
      'hcluster':features+[field('clusters','Clusters','군집 수','number','2'),choice('linkage','Linkage','연결 방법','ward',[(v,v.title(),v.title()) for v in ('ward','single','complete','average')]),scaling],
    }
